name: Build and Deploy
on: workflow_dispatch
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: hosting125544.a2fe2.netcup.net
        username: bibelleseplan.missionsteam-dn.de
        password: ${{ secrets.password }}
        local-dir: ./